name: jd_v4_bot-sync
on:
  schedule:
    - cron: '1 * */7 * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-Annyoo2021-jd_v4_bot
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync Annyoo2021-jd_v4_bot
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/Annyoo2021/jd_v4_bot.git"
          source_branch: "main"
          destination_branch: "Annyoo2021"
          github_token: ${{ secrets.PAT }}
